name: ignis_insight
description: Projeto que utiliza Inteligência Artificial para recomendar óculos.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: 
  flutter_secure_storage:
  get:
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  faker:
  flutter_launcher_icons: 
  flutter_lints: ^2.0.0
  mocktail: 
  test: 

flutter:
  uses-material-design: true

  assets:
    - assets/icons/icon.png
    - assets/images/
    - assets/images/formats/
    - assets/images/measures/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf

flutter_icons:
  ios: true
  android: true
  image_path_android: assets/icons/icon.png
  image_path_ios: assets/icons/icon.png